name: Changelog required
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  enforce:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Falhar se o PR não tocar CHANGELOG.md
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          CHANGED=$(git diff --name-only HEAD origin/${{ github.base_ref }})
          echo "$CHANGED"
          echo "$CHANGED" | grep -q "CHANGELOG.md"
